version: '3.8'

services:
  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/clara-neo4j
      # - NEO4J_dbms_connector_https_advertised__address=localhost:7473
      # - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      # - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "clara-neo4j", "RETURN 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build: .
    depends_on:
      neo4j:
        condition: service_healthy
    working_dir: /app
    ports:
      - "8088:8088"

volumes:
  neo4j_data:
  neo4j_logs: